### ISSUE TITLE
Build - Initial Setup

### ISSUE THREAD

**Issue by GeorgeCiesinski** [GeorgeCiesinski/portfolio-blog#1]
Setup a local version of the site. 

# Checks

- [x] PHP version
- [x] Composer version
- [x] MariaDB Version

# Tasks

- [x] Create local database
- [x] Setup Apache Server
- [x] Setup Virtual Hosts
- [x] Install site
- [x] Configuration

# Instructions

- https://getgrav.org/blog/macos-sonoma-apache-multiple-php-versions
- https://blog.devops.dev/how-to-install-apache-mysql-phpmyadmin-server-on-macos-ventura-c65e68387776
- https://www.git-tower.com/blog/apache-on-macos/

**Comment by GeorgeCiesinski** [comment]
Downloaded MySQLWorkbench.

**Comment by GeorgeCiesinski** [comment]
I encountered significant issues with my Apache setup which took over a week to resolve. 

- [ ] Confirm Apache config is correct
- [ ] Confirm PHP config is correct
- [ ] Check permissions
- [ ] Check permissions going up each directory

**Comment by GeorgeCiesinski** [comment]
After further troubleshooting, this issue is still happening. I found a discussion on the homebrew github where someone else reported this. I updated it with my own error logs: 

https://github.com/orgs/Homebrew/discussions/4915

**Comment by GeorgeCiesinski** [comment]
Solution found. Description below. 

I found another discussion about a similar error: https://github.com/orgs/Homebrew/discussions/3525

This discussion advised to check the error log where I found the suggestion to try running `/opt/homebrew/opt/httpd/bin/httpd -D FOREGROUND` and see what it outputs. 

```
georgeciesinski@georges-air ~ % /opt/homebrew/opt/httpd/bin/httpd -D FOREGROUND
(13)Permission denied: AH00091: httpd: could not open error log file /opt/homebrew/var/log/httpd/error_log.
```

# Check permissions of error_log

Seeing how it didn't have permission to access the error_log I checked this next. 

```
georgeciesinski@georges-air httpd % ls -al
total 112
drwxr-xr-x  4 georgeciesinski  admin    128 21 Jun  2023 .
drwxr-xr-x  6 georgeciesinski  admin    192 20 May 20:02 ..
-rw-r--r--  1 root             admin  29727 20 May 19:13 access_log
-rw-r--r--  1 root             admin  22508 20 May 19:17 error_log
```

# Modify Permissions

Next, I found [this post](https://bobcares.com/blog/httpd-could-not-open-error-log-file/) which suggested to change the permissions to 666. 

```
georgeciesinski@georges-air httpd % sudo chmod 666 error_log
georgeciesinski@georges-air httpd % sudo chmod 666 access_log
```

# Testing

I tailed the error_log and ran the command again.

```
georgeciesinski@georges-air ~ % /opt/homebrew/opt/httpd/bin/httpd -D FOREGROUND
```

The error log showed the command and seemed to be working. I killed the command, and tried launching it as a service again. 

```
georgeciesinski@georges-air ~ % brew services start httpd
==> Successfully started `httpd` (label: homebrew.mxcl.httpd)
georgeciesinski@georges-air ~ % brew services list
Name  Status  User            File
httpd started georgeciesinski ~/Library/LaunchAgents/homebrew.mxcl.httpd.plist
mysql started georgeciesinski ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
php   started georgeciesinski ~/Library/LaunchAgents/homebrew.mxcl.php.plist
```

Success.

**Comment by GeorgeCiesinski** [comment]
In light of possible changes from Oracle, I decided to go with MariaDB instead of MySQL. I spent today figuring out how to get it working in homebrew and was able to get it working sucessfully after much trial and error.

**Comment by GeorgeCiesinski** [comment]
Closing as complete.
