### ISSUE TITLE
Build - Blog

### ISSUE THREAD

**Issue by GeorgeCiesinski** [GeorgeCiesinski/portfolio-blog#2]
Create the infrastructure required for the blog. 

# Tasks

- [x] Create Blog content-type
- [x] Create tagging taxonomy
- [x] Create view
- [x] Create filters
- [x] First blog post
