### ISSUE TITLE
Research - Hosting

### ISSUE THREAD

**Issue by GeorgeCiesinski** [GeorgeCiesinski/portfolio-blog#7]
Where will this website be hosted? Additionally, what will the domain name be, and how much will everything cost? 

# Todo

- [x] Research [Hostinger](https://www.hostinger.com/drupal-hosting)
- [x] Research domain name cost and renewal
- [ ] Determine some domain name options

# After finding host

- [x] Determine what mysql version host allows
- [x] Determine risks of using mysql over mariadb
- [x] Plan out a target date to push portfolio & blog site

**Comment by GeorgeCiesinski** [comment]
Hostinger plan costs $2.69-2.99USD / mo for 48 months (plus 3 months free). This should last me approximately until the world ends. 

This changes to $7.99USD / mo afterwards.

The domain is free for the first year and should cost about $10-20USD / year afterwards. This includes `.me` and `.io` domains, but not `.dev`.

**Comment by GeorgeCiesinski** [comment]
Decided to go with MariaDB to avoid MySQL possibly changing source code in the future. Installed site. Closing issue as the domain name can be determined at a future date.
